# Generated by Django 3.0.4 on 2020-05-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityManagement', '0003_auto_20200422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='register_num',
            field=models.IntegerField(),
        ),
    ]
