# Generated by Django 2.2.11 on 2020-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to admin site', verbose_name='staff status'),
        ),
    ]
