# Generated by Django 2.2.11 on 2020-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, help_text='This saves the activation key sent at the creation of the account.When logged in, if this is True, the user is asked to activate the account.', max_length=10, verbose_name='activation key'),
        ),
        migrations.AddField(
            model_name='user',
            name='key_expiry',
            field=models.DateTimeField(default=None, null=True, verbose_name='key expiry'),
        ),
    ]
