# Generated by Django 2.2.11 on 2020-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0003_auto_20200331_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_reports',
            field=models.BooleanField(default=True, verbose_name='reception of monthly reports'),
        ),
    ]
