# Generated by Django 3.0.4 on 2020-04-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountManagement', '0004_user_receive_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_reports',
            field=models.BooleanField(default=True, verbose_name='reception of Monthly Reports'),
        ),
    ]
