# Generated by Django 3.0.4 on 2020-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('total_count', models.IntegerField()),
                ('peak_hour_start', models.TimeField()),
                ('peak_hour_end', models.TimeField()),
            ],
        ),
    ]
